# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"

[plugins]

[plugins.zsh-defer]
github = "romkatv/zsh-defer"
apply = ["source"]

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
apply = ["defer"]

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"
apply = ["defer"]

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"
apply = ["defer"]

[plugins.enhancd]
github = "b4b4r07/enhancd"

[plugins.gitignore]
github = "voronkovich/gitignore.plugin.zsh"

# cf. https://bucci.bp7.org/archives/48515/
[plugins.fzf]
github = "junegunn/fzf"
apply = ['fzf-install', 'fzf-source']

[plugins.forgit]
github = "wfxr/forgit"
rev = "25.02.0"
use = ["forgit.plugin.zsh"]
apply = ["source", "forgit-bin", "forgit-copy", "forgit-graph"]

[plugins.zabrze]
inline = 'eval "$(zabrze init --bind-keys)"'

[plugins.starship]
inline = 'eval "$(starship init zsh)"'

[plugins.mise]
inline = """
eval "$(mise activate zsh)"
eval "$(mise activate --shims)"
"""

[templates]
PATH = 'export PATH="$PATH:{{ dir }}"'
defer = "{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}"
fzf-install = "{{ dir }}/install --bin > /dev/null \n[[ ! $PATH =~ {{ dir }} ]] && export PATH=\"$PATH:{{ dir }}/bin\"\n"
fzf-source = "{% for file in files %}source \"{{ file }}\"\n{% endfor %}"
forgit-bin = 'PATH="$PATH:$FORGIT_INSTALL_DIR/bin"'
forgit-copy = "export FORGIT_COPY_CMD='bp'"
forgit-graph = "export FORGIT_LOG_GRAPH_ENABLE=true"
